import Footer from '@/components/Shared/Footer'
import Navbar from '@/components/Shared/Navbar'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Next.js App Router',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (

        <>
            <Navbar />
            <div className='min-h-screen'>
                {children}
            </div>
            <Footer />
        </>

    )
}
